// src/components/buttons/SpeedControlButton.vue
<template>
  <WithPopper
    :popper-text="'Change Speed'"
    :is-popper-active="isPopperActive"
    :class="[
      'vdb-p-transition',
      autoHide && !showElements ? 'vdb-p-opacity-0' : 'vdb-p-opacity-1',
    ]"
  >
    <template #button>
      <TransparentButton
        class="vdb-p-w-48 vdb-p-h-40 vdb-p-ml-8 vdb-p-pale vdb-p-group"
        :default-state-css="'vdb-p-bg-black-16 vdb-p-border vdb-p-border-white-16 vdb-p-backdrop-blur hover:vdb-p-bg-random-313131 hover:vdb-p-border-random-8e6200'"
        :disabled-state-css="'vdb-p-bg-black-45 vdb-p-opacity-20 vdb-p-backdrop-blur vdb-p-cursor-not-allowed vdb-p-pointer-events-none'"
        :button-state="isActive ? 'default' : 'hidden'"
        @click-action="onClickPlaybackRate"
      >
        <!-- Speed Indicator-->
        <div class="vdb-p-text-white">{{ playBackRate }}x</div>
      </TransparentButton>
    </template>
  </WithPopper>
</template>

<script setup>
import { ref } from "vue";
import TransparentButton from "../atoms/TransparentButton.vue";
import WithPopper from "../atoms/WithPopper.vue";
import { useVideoDBPlayer } from "../../context.js";

const props = defineProps({
  isActive: {
    type: Boolean,
    default: true,
  },
  speedOptions: {
    type: Array,
    default: () => [1, 1.2, 1.5, 1.8, 2],
  },
  autoHide: {
    type: Boolean,
    default: true,
  },
});

const isPopperActive = ref(true);

const { playBackRate, setPlayBackRate, showElements } = useVideoDBPlayer();

const onClickPlaybackRate = () => {
  const newValue =
    props.speedOptions[
      (props.speedOptions.indexOf(playBackRate.value) + 1) %
        props.speedOptions.length
    ];
  setPlayBackRate(newValue);
};
</script>

// player-react/src/components/buttons/speed-control-button/index.tsx
import React, { JSX } from "react";
import { useVideoPlayerContext } from "../../../context";
import TransparentButton from "../../atoms/transparent-btn";
import WithPopper from "../../atoms/with-popper";

interface PlaybackRateButtonProps {
  isActive?: boolean;
  autoHide?: boolean;
  speedOptions?: number[];
}

export default function SpeedControlButton({
  isActive = true,
  autoHide = true,
  speedOptions = [1, 1.2, 1.5, 1.8, 2],
}: PlaybackRateButtonProps): JSX.Element {
  const { playBackRate, setPlayBackRate, showElements } =
    useVideoPlayerContext();
  const isPopperActive = true;

  const opacityClass =
    autoHide && !showElements ? "vdb-p-opacity-0" : "vdb-p-opacity-1";

  const onClickPlaybackRate = () => {
    const currentIndex = speedOptions.indexOf(playBackRate);
    const nextIndex = (currentIndex + 1) % speedOptions.length;
    setPlayBackRate(speedOptions[nextIndex]);
  };

  return (
    <WithPopper
      popperText="Change Speed"
      isPopperActive={isPopperActive}
      className={`vdb-p-transition ${opacityClass}`}
    >
      <TransparentButton
        className="vdb-p-pale vdb-p-group vdb-p-ml-8 vdb-p-h-40 vdb-p-w-48"
        defaultStateCss="vdb-p-bg-black-16 vdb-p-border vdb-p-border-white-16 vdb-p-backdrop-blur hover:vdb-p-bg-random-313131 hover:vdb-p-border-random-8e6200"
        disabledStateCss="vdb-p-bg-black-45 vdb-p-opacity-20 vdb-p-backdrop-blur vdb-p-cursor-not-allowed vdb-p-pointer-events-none"
        buttonState={isActive ? "default" : "hidden"}
        onClickAction={onClickPlaybackRate}
      >
        <div className="vdb-p-text-white">{playBackRate}x</div>
      </TransparentButton>
    </WithPopper>
  );
}
