// packages/player-react/src/components/videos/progress-bar/index.tsx
import debounce from "lodash.debounce";
import React, {
  JSX,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import videojs from "video.js";
import Player from "video.js/dist/types/player";
import { useVideoPlayerContext } from "../../../context";
import "./index.css";

interface Chapter {
  id?: string | number;
  start: number;
  length: number;
  title?: string;
  end?: number;
}

interface Props {
  isActive?: boolean;
  autoHide?: boolean;
  streamUrl?: string;
  chaptersList?: Chapter[];
  persistentChapter?: boolean;
  manualSlide?: number | null;
  activeChapterProp?: string | null;
  showChapters?: boolean;
  previewPlayer?: string;
  isChapterExpanded?: boolean;
  setActiveChapter?: (chapterIndex: number | null) => void;
  hideChapterSummary?: (isVisible: boolean) => void;
  setPreviewVisibility?: (isVisible: boolean) => void;
}

export default function ProgressBar({
  isActive = true,
  autoHide = true,
  streamUrl = "",
  chaptersList = [],
  persistentChapter = false,
  manualSlide = null,
  activeChapterProp: activeChapterPropRaw = null,
  showChapters = false,
  isChapterExpanded = false,
  setActiveChapter = () => {},
  hideChapterSummary = () => {},
  setPreviewVisibility = () => {},
}: Props): JSX.Element {
  const { time, duration, seekTo, showElements } = useVideoPlayerContext();

  const feedbackPlayerRef = useRef<Player | null>(null);
  const progressBarRef = useRef<HTMLDivElement>(null);
  const videoPreviewRef = useRef<HTMLDivElement>(null);
  const progressBarInteractRef = useRef<HTMLDivElement>(null);
  const videoFeedbackPlayerRef = useRef<HTMLVideoElement>(null);

  const [moveToRatio, setMoveToRatio] = useState(0);
  const [videoDrag, setVideoDrag] = useState(false);
  const [seekGoToPoint, setSeekGoToPoint] = useState({
    ratio: 0,
    timePosition: 0,
  });
  const [showSummaryInfo, setShowSummaryInfo] = useState(true);
  const [activeChapterLocal, setActiveChapterLocal] = useState<number | null>(
    activeChapterPropRaw !== null ? Number(activeChapterPropRaw) : null,
  );
  const [leftOffset, setLeftOffset] = useState(0);

  useEffect(() => {
    setActiveChapterLocal(
      activeChapterPropRaw !== null ? Number(activeChapterPropRaw) : null,
    );
  }, [activeChapterPropRaw]);

  useEffect(() => {
    setActiveChapter(activeChapterLocal);
  }, [activeChapterLocal, setActiveChapter]);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const isWide = window.innerWidth > 640;
      const maxRatio = isWide ? 11 / 12 : 10.5 / 12;
      const minRatio = isWide ? 1 / 12 : 1.5 / 12;
      const clampedRatio = Math.max(Math.min(moveToRatio, maxRatio), minRatio);
      setLeftOffset(clampedRatio * 100);
    }
  }, [moveToRatio]);

  const videoDateVal = useMemo(() => {
    if (!duration || !moveToRatio) return 0;
    return moveToRatio * duration * 1000;
  }, [duration, moveToRatio]);

  const shouldNotShowVideoPopover = useMemo(() => {
    if (typeof window === "undefined") return true;
    if (showChapters) {
      return (
        activeChapterLocal === null ||
        moveToRatio === 0 ||
        (window.innerWidth < 640 && persistentChapter)
      );
    }
    return moveToRatio === 0;
  }, [showChapters, activeChapterLocal, moveToRatio, persistentChapter]);

  const summaryCardVisible = useMemo(() => {
    const overlapThreshold = isChapterExpanded ? 0.22 : 0.52;
    if (activeChapterPropRaw === null) return false;
    if (persistentChapter) {
      return moveToRatio > overlapThreshold;
    }
    return true;
  }, [isChapterExpanded, activeChapterPropRaw, persistentChapter, moveToRatio]);

  const isSummaryCardOverlapping = useMemo(() => {
    return summaryCardVisible && persistentChapter;
  }, [summaryCardVisible, persistentChapter]);

  useEffect(() => {
    hideChapterSummary(isSummaryCardOverlapping);
  }, [isSummaryCardOverlapping, hideChapterSummary]);

  const summaryHiddenOnceRef = useRef(false);
  useEffect(() => {
    if (moveToRatio > 0 && showSummaryInfo && !summaryHiddenOnceRef.current) {
      summaryHiddenOnceRef.current = true;
      const timer = setTimeout(() => {
        setShowSummaryInfo(false);
      }, 2000);
      return () => clearTimeout(timer);
    }
  }, [moveToRatio, showSummaryInfo]);

  useEffect(() => {
    setPreviewVisibility(moveToRatio > 0);
  }, [moveToRatio, setPreviewVisibility]);

  useEffect(() => {
    const getSource = () => {
      const src = streamUrl;
      if (!src) return null;
      let type = "video/mp4";
      if (src.endsWith("m3u8")) {
        type = "application/x-mpegURL";
      }
      return { src, type };
    };
    const source = getSource();

    if (videoFeedbackPlayerRef.current && source) {
      if (!feedbackPlayerRef.current) {
        feedbackPlayerRef.current = videojs(videoFeedbackPlayerRef.current, {
          autoplay: false,
          controls: false,
          currentTime: 0,
          html5: { nativeTextTracks: false },
          preload: "auto",
          sources: [source],
        });
      }
    }
    return () => {
      if (
        feedbackPlayerRef.current &&
        !feedbackPlayerRef.current.isDisposed()
      ) {
        feedbackPlayerRef.current.dispose();
        feedbackPlayerRef.current = null;
      }
    };
  }, [streamUrl]);

  const findCurrentChapter = useCallback(
    (timeToCheck: number): number | null => {
      if (duration === 0) return null;
      const referenceTime = Math.min(Math.max(timeToCheck, 0), duration);
      for (let i = 0; i < chaptersList.length; i++) {
        const chapter = chaptersList[i];
        if (
          chapter.start <= referenceTime &&
          chapter.start + chapter.length > referenceTime
        ) {
          return i;
        }
      }
      return null;
    },
    [chaptersList, duration],
  );

  const updateFeedbackPlayer = useCallback(
    debounce((t: number) => {
      if (
        feedbackPlayerRef.current &&
        !feedbackPlayerRef.current.isDisposed()
      ) {
        feedbackPlayerRef.current.currentTime(t);
      }
    }, 300),
    [],
  );

  const seekVideoTimeCallback = useCallback(
    (x: number) => {
      if (!progressBarRef.current || duration === 0) {
        return;
      }
      const rect = progressBarRef.current.getBoundingClientRect();
      let position = x - rect.left;
      const totalWidth = rect.width;

      position = Math.max(0, Math.min(position, totalWidth));

      const newRatio = position / totalWidth;
      const newTimePosition = Math.round(duration * newRatio);

      setSeekGoToPoint({
        ratio: newRatio,
        timePosition: newTimePosition,
      });
    },
    [duration, setSeekGoToPoint],
  );

  const handleDragStartMouseDown = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      setVideoDrag(true);
      seekVideoTimeCallback(e.pageX);
    },
    [seekVideoTimeCallback, setVideoDrag],
  );

  const handleDragStartTouchStart = useCallback(
    (e: React.TouchEvent<HTMLDivElement>) => {
      if (e.touches.length > 0) {
        setVideoDrag(true);
        seekVideoTimeCallback(e.touches[0].clientX);
      }
    },
    [seekVideoTimeCallback, setVideoDrag],
  );

  // Effect for managing global event listeners during drag
  useEffect(() => {
    const handleWindowMouseMove = (e: MouseEvent) => {
      seekVideoTimeCallback(e.pageX);
    };

    const handleWindowTouchMove = (e: TouchEvent) => {
      if (e.touches.length > 0) {
        seekVideoTimeCallback(Math.floor(e.touches[0].clientX));
      }
    };

    const handleWindowMouseUp = () => {
      setVideoDrag(false);
      seekTo(seekGoToPoint.timePosition);
      if (persistentChapter) {
        const chapter = findCurrentChapter(seekGoToPoint.timePosition);
        setActiveChapterLocal(chapter);
      }
    };

    const handleWindowTouchEnd = () => {
      setVideoDrag(false);
      seekTo(Math.floor(seekGoToPoint.timePosition));
      setMoveToRatio(0); // Reset hover ratio
      if (!persistentChapter) {
        setActiveChapterLocal(null);
      }
    };

    if (videoDrag) {
      window.addEventListener("mousemove", handleWindowMouseMove);
      window.addEventListener("touchmove", handleWindowTouchMove, {
        passive: true,
      }); // passive: false if preventDefault is used
      window.addEventListener("mouseup", handleWindowMouseUp);
      window.addEventListener("touchend", handleWindowTouchEnd);

      return () => {
        window.removeEventListener("mousemove", handleWindowMouseMove);
        window.removeEventListener("touchmove", handleWindowTouchMove);
        window.removeEventListener("mouseup", handleWindowMouseUp);
        window.removeEventListener("touchend", handleWindowTouchEnd);
      };
    }
  }, [
    videoDrag,
    seekVideoTimeCallback,
    seekTo,
    persistentChapter,
    findCurrentChapter,
    setActiveChapterLocal,
    setMoveToRatio,
    seekGoToPoint, // Ensure latest seekGoToPoint is used in up/end handlers
  ]);

  // --- Hover and Click Logic on progressBarInteract ---
  const handleMouseMoveForHover = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      if (!progressBarRef.current || duration === 0) return;
      const rect = progressBarRef.current.getBoundingClientRect();
      const tempRatio = (e.clientX - rect.x) / rect.width;

      const currentMoveToRatio = Math.min(Math.max(0, tempRatio), 1); // Clamp between 0 and 1
      setMoveToRatio(currentMoveToRatio);

      const newTime = duration * currentMoveToRatio;
      updateFeedbackPlayer(newTime);

      if (chaptersList.length > 0) {
        setActiveChapterLocal(findCurrentChapter(newTime));
      } else {
        setActiveChapterLocal(null); // Vue had `true`, null seems more appropriate
      }
    },
    [
      duration,
      updateFeedbackPlayer,
      chaptersList,
      findCurrentChapter,
      setMoveToRatio,
      setActiveChapterLocal /* progressBarRef is stable */,
    ],
  );

  const handleMouseLeaveForHover = useCallback(() => {
    // Reset active chapter and hover ratio if not dragging
    if (!videoDrag) {
      // Only reset if not in midst of a drag
      setActiveChapterLocal(null);
      setMoveToRatio(0);
      // Potentially reset showSummaryInfo if it should reappear
      // setShowSummaryInfo(true);
      // summaryHiddenOnceRef.current = false;
    }
  }, [setActiveChapterLocal, setMoveToRatio, videoDrag]);

  const handleTouchMoveOnProgressBar = useCallback(
    (e: React.TouchEvent<HTMLDivElement>) => {
      if (e.touches.length > 0 && progressBarRef.current && duration > 0) {
        e.preventDefault(); // Prevent scrolling while scrubbing preview
        const clientX = e.touches[0].clientX;
        const rect = progressBarRef.current.getBoundingClientRect();
        const tempRatio = (clientX - rect.left) / rect.width;

        const currentMoveToRatio = Math.min(Math.max(0, tempRatio), 1);
        setMoveToRatio(currentMoveToRatio);

        const newTime = duration * currentMoveToRatio;
        updateFeedbackPlayer(newTime);

        if (chaptersList.length > 0) {
          setActiveChapterLocal(findCurrentChapter(newTime));
        } else {
          setActiveChapterLocal(null);
        }
      }
    },
    [
      duration,
      updateFeedbackPlayer,
      chaptersList,
      findCurrentChapter,
      setMoveToRatio,
      setActiveChapterLocal /* progressBarRef stable */,
    ],
  );

  const handleProgressClick = useCallback(() => {
    if (duration > 0) {
      const goTo = duration * moveToRatio; // moveToRatio is from hover state
      seekTo(goTo);
    }
  }, [duration, moveToRatio, seekTo]);

  const getActiveChapterTitle = useCallback(() => {
    if (activeChapterLocal === null || !chaptersList[activeChapterLocal])
      return "";
    return chaptersList[activeChapterLocal]?.title || "";
  }, [chaptersList, activeChapterLocal]);

  const isManuallySlid = (key: number) => {
    return persistentChapter && manualSlide === key && moveToRatio === 0;
  };

  const isActiveChapter = (key: number) => {
    // Vue: isActiveChapter(key) && (persistentChapter && manualSlide && !moveToRatio ? isManuallySlid(key) : true)) || isManuallySlid(key)
    // This logic in React becomes:
    const currentlyActive = activeChapterLocal === key;
    const manuallySlid = isManuallySlid(key);

    if (manuallySlid) return true;
    if (currentlyActive) {
      if (
        persistentChapter &&
        manualSlide !== null &&
        manualSlide <= key &&
        moveToRatio === 0
      ) {
        // Check this condition. Vue had manualSlide >= key for manualSlid class
        return isManuallySlid(key); // Which means if manualSlide is not key, it's false. So it means only if it *is* manually slid.
      }
      return true;
    }
    return false;
  };

  const headLeftPercent = videoDrag
    ? seekGoToPoint.ratio * 100
    : duration > 0
      ? (time / duration) * 100
      : 0;

  return (
    <div className="vdb-p-w-full">
      <div
        className={`progress-bar vdb-p-relative vdb-p-flex vdb-p-h-8 vdb-p-items-center vdb-p-transition-opacity ${
          isActive ? "" : "vdb-p-hidden" // Using hidden instead of conditional rendering for simplicity if preferred
        } ${
          (autoHide && !showElements) || duration === 0
            ? "vdb-p-opacity-0"
            : "vdb-p-opacity-1"
        }`}
        ref={progressBarRef}
      >
        <div
          ref={videoPreviewRef}
          className={`vdb-p-pointer-events-none vdb-p-absolute vdb-p-bottom-28 vdb-p-left-0 vdb-p-w-2/12 vdb-p-min-w-112 vdb-p--translate-x-1/2 vdb-p-transform vdb-p-rounded-b-8 vdb-p-pb-2 sm:vdb-p-bottom-16 sm:vdb-p-pb-4 ${
            shouldNotShowVideoPopover ? "vdb-p-opacity-0" : "vdb-p-opacity-100"
          }`}
          style={{
            left: `${leftOffset}%`,
            zIndex: 29,
          }}
        >
          <div className="vdb-p-relative vdb-p-w-full">
            <div
              className="vdb-p-relative vdb-p-mb-4 vdb-p-w-full sm:vdb-p-mb-4"
              style={{ paddingBottom: "56.25%" }}
            >
              <video
                ref={videoFeedbackPlayerRef}
                className="video-js vdb-p-bottom-0 vdb-p-left-0 !vdb-p-h-full !vdb-p-w-full vdb-p-rounded-4 vdb-p-border-2 vdb-p-border-white"
                style={{ position: "absolute" }}
                playsInline
                preload="metadata"
              />
            </div>
          </div>
          {showChapters && (
            <div className="chapter-title-cont vdb-p-relative vdb-p-flex vdb-p-items-center vdb-p-justify-center vdb-p-transition-all">
              <p className="three-line-ellipses title-blur vdb-p-h-auto vdb-p-max-h-full vdb-p-w-full vdb-p-rounded-8 vdb-p-p-8 vdb-p-text-center vdb-p-font-primary vdb-p-text-lg vdb-p-capitalize vdb-p-text-white">
                {activeChapterLocal !== null
                  ? `${activeChapterLocal + 1}. `
                  : ""}
                {getActiveChapterTitle()}
              </p>
            </div>
          )}
          <p className="text-shadow vdb-p-w-full vdb-p-whitespace-nowrap vdb-p-text-center vdb-p-text-xs vdb-p-font-medium vdb-p-text-white">
            <span>
              {new Date(videoDateVal || 0).toISOString().substring(11, 19)}
            </span>
          </p>
        </div>

        {/* Main timelines */}
        <div className="main-timeline vdb-p-absolute vdb-p-left-0 vdb-p-top-2 vdb-p-w-full">
          {chaptersList.length === 0 ? (
            <div
              className={`chapter vdb-p-w-full vdb-p-backdrop-blur-lg ${
                // Assuming .chapter has height, bg etc.
                activeChapterLocal !== null ? "active" : "" // 'active' class might need specific styling
              }`}
            >
              {/* Seekbar */}
              <div
                className="vdb-p-absolute vdb-p-left-0 vdb-p-top-0 vdb-p-h-full vdb-p-bg-white vdb-p-shadow-2" // seekbar needs base styling from .chapter
                style={{
                  width: videoDrag
                    ? `${seekGoToPoint.ratio * 100}%`
                    : duration > 0
                      ? `${(time / duration) * 100}%`
                      : "0%",
                }}
              />
              {/* Hover fade bar */}
              <div
                className={`vdb-p-pointer-events-none vdb-p-absolute vdb-p-left-0 vdb-p-top-0 vdb-p-h-full vdb-p-bg-white vdb-p-shadow-2 ${
                  activeChapterLocal !== null // Based on hover, not main playhead
                    ? "vdb-p-opacity-40"
                    : "vdb-p-opacity-0"
                }`}
                style={{
                  width: `${moveToRatio * 100}%`,
                }}
              />
            </div>
          ) : (
            <div className="chaptersCont vdb-p-flex vdb-p-items-center vdb-p-gap-2">
              {chaptersList.map((chapter, key) => (
                <div
                  key={chapter.id || String(chapter.end) || key} // Ensure a unique key
                  className={`chapter ${
                    // Base .chapter styles needed
                    isActiveChapter(key) ? "active" : ""
                  } ${
                    persistentChapter &&
                    manualSlide !== null &&
                    manualSlide >= key &&
                    moveToRatio === 0
                      ? "manualSlid"
                      : ""
                  }`}
                  style={{
                    width:
                      duration > 0
                        ? `${(chapter.length / duration) * 100}%`
                        : "0%",
                    maxWidth:
                      duration > 0
                        ? `${(chapter.length / duration) * 100}%`
                        : "0%",
                  }}
                >
                  {/* Hover faded bar */}
                  <div
                    className="vdb-p-pointer-events-none vdb-p-absolute vdb-p-left-0 vdb-p-top-0 vdb-p-hidden vdb-p-h-full vdb-p-bg-white vdb-p-shadow-2 md:vdb-p-block"
                    style={{
                      width:
                        chapter.length > 0
                          ? `${
                              Math.max(
                                0,
                                Math.min(
                                  1,
                                  (moveToRatio * duration - chapter.start) /
                                    chapter.length,
                                ),
                              ) * 100
                            }%`
                          : "0%",
                    }}
                  />
                  {/* Seekbar */}
                  <div
                    className="vdb-p-absolute vdb-p-left-0 vdb-p-top-0 vdb-p-h-full vdb-p-bg-primary" // Primary color for played part
                    style={{
                      width:
                        chapter.length > 0
                          ? `${
                              Math.max(
                                0,
                                Math.min(
                                  1,
                                  ((videoDrag
                                    ? seekGoToPoint.ratio * duration
                                    : time) -
                                    chapter.start) /
                                    chapter.length,
                                ),
                              ) * 100
                            }%`
                          : "0%",
                    }}
                  />
                </div>
              ))}
            </div>
          )}
        </div>

        <div
          ref={progressBarInteractRef}
          className="vdb-p-absolute vdb-p--bottom-2 vdb-p-left-0 vdb-p-right-0 vdb-p-top-4 vdb-p-cursor-pointer sm:vdb-p--bottom-3 sm:vdb-p-top-3"
          onMouseDown={handleDragStartMouseDown}
          onTouchStart={handleDragStartTouchStart}
          onMouseMove={handleMouseMoveForHover}
          onMouseLeave={handleMouseLeaveForHover}
          onTouchMove={handleTouchMoveOnProgressBar}
          onClick={handleProgressClick}
        >
          <div
            className={`head vdb-p-align-center vdb-p-absolute vdb-p-top-0 vdb-p-z-10 vdb-p-flex vdb-p-h-10 vdb-p-w-10 vdb-p--translate-x-1/2 vdb-p--translate-y-1/2 vdb-p-transform vdb-p-cursor-pointer vdb-p-overflow-visible vdb-p-rounded-full vdb-p-border-2 vdb-p-border-outline-light vdb-p-bg-primary vdb-p-shadow-3 vdb-p-transition sm:vdb-p-h-14 sm:vdb-p-w-14 sm:vdb-p--translate-y-1/4 ${
              duration > 0 && time / duration <= 0.1
                ? "vdb-p-justify-start"
                : duration > 0 && time / duration >= 0.9
                  ? "vdb-p-justify-end"
                  : "vdb-p-justify-center"
            }`}
            style={{
              left: `${headLeftPercent}%`,
            }}
          >
            <span
              className={`vdb-p-pointer-events-none vdb-p-absolute vdb-p-flex vdb-p--translate-y-20 vdb-p-transform vdb-p-text-caption2 vdb-p-transition-opacity sm:vdb-p-hidden ${
                isActive && !persistentChapter && !videoDrag
                  ? "vdb-p-opacity-100"
                  : "vdb-p-opacity-0"
              }`}
            >
              <span className="vdb-p-text-white">
                {new Date(time * 1000).toISOString().substring(11, 19)}
              </span>
              <span className="vdb-p-text-kilvish-500">
                 / 
                {new Date(duration * 1000).toISOString().substring(11, 19)}
              </span>
            </span>
          </div>
        </div>
      </div>
      {/* Fallback for when not active */}
      {!isActive && (
        <div className="progress-bar vdb-p-mb-12 vdb-p-h-4 vdb-p-w-full vdb-p-bg-black-16 vdb-p-opacity-0"></div>
      )}
    </div>
  );
}

// src/components/video/ProgressBar.vue
<template>
  <div class="vdb-p-w-full">
    <div
      v-show="isActive"
      ref="progressBar"
      :class="[
        'progress-bar vdb-p-relative vdb-p-flex vdb-p-h-8 vdb-p-items-center vdb-p-transition-opacity',
        (autoHide && !showElements) || duration === 0
          ? 'vdb-p-opacity-0'
          : 'vdb-p-opacity-1',
      ]"
    >
      <!-- Video feedback popover -->
      <div
        ref="videoPreview"
        class="vdb-p-pointer-events-none vdb-p-absolute vdb-p-bottom-28 vdb-p-left-0 vdb-p-w-2/12 vdb-p-min-w-112 vdb-p--translate-x-1/2 vdb-p-transform vdb-p-rounded-b-8 vdb-p-pb-2 sm:vdb-p-bottom-16 sm:vdb-p-pb-4"
        :class="{
          'vdb-p-opacity-0': shouldNotShowVideoPopover,
        }"
        :style="{
          left: `${
            Math.max(
              Math.min(moveToRatio, innerWidth() > 640 ? 11 / 12 : 10.5 / 12),
              innerWidth() > 640 ? 1 / 12 : 1.5 / 12,
            ) * 100
          }%`,
          zIndex: 29,
        }"
      >
        <div class="vdb-p-relative vdb-p-w-full">
          <div
            class="vdb-p-relative vdb-p-mb-4 vdb-p-w-full sm:vdb-p-mb-4"
            style="padding-bottom: 56.25%"
          >
            <video
              ref="videoFeedbackPlayer"
              class="video-js vdb-p-bottom-0 vdb-p-left-0 vdb-p-h-full vdb-p-w-full vdb-p-rounded-4 vdb-p-border-2 vdb-p-border-white"
              style="position: absolute"
              playsinline
              preload
            />
          </div>
        </div>
        <div
          v-if="showChapters"
          class="chapter-title-cont vdb-p-relative vdb-p-flex vdb-p-items-center vdb-p-justify-center vdb-p-transition-all"
        >
          <p
            class="three-line-ellipses title-blur vdb-p-h-auto vdb-p-max-h-full vdb-p-w-full vdb-p-rounded-8 vdb-p-p-8 vdb-p-text-center vdb-p-font-primary vdb-p-text-lg vdb-p-capitalize vdb-p-text-white"
          >
            {{ activeChapter + 1 }}. {{ getActiveChapterTitle() }}
          </p>
        </div>
        <p
          class="text-shadow vdb-p-w-full vdb-p-whitespace-nowrap vdb-p-text-center vdb-p-text-xs vdb-p-font-medium vdb-p-text-white"
        >
          <span>
            {{ new Date(videoDateVal || 0).toISOString().substring(11, 19) }}
          </span>
        </p>
      </div>
      <!-- Main timelines -->
      <div
        class="main-timeline vdb-p-absolute vdb-p-left-0 vdb-p-top-2 vdb-p-w-full"
      >
        <!-- If no chapters -->
        <div
          v-if="chaptersList.length === 0"
          class="chapter vdb-p-w-full vdb-p-backdrop-blur-lg"
          :class="{ active: activeChapter }"
        >
          <!-- Seekbar -->
          <div
            class="vdb-p-absolute vdb-p-left-0 vdb-p-top-0 vdb-p-h-full vdb-p-bg-white vdb-p-shadow-2"
            :style="{
              width: videoDrag
                ? `${100 * seekGoToPoint.ratio}%`
                : `${(100 * time) / duration}%`,
            }"
          />
          <!-- Hover fade bar -->
          <div
            class="vdb-p-pointer-events-none vdb-p-absolute vdb-p-left-0 vdb-p-top-0 vdb-p-h-full vdb-p-bg-white vdb-p-shadow-2"
            :class="
              activeChapter !== null ? 'vdb-p-opacity-40' : 'vdb-p-opacity-0'
            "
            :style="{
              width: `${100 * moveToRatio}%`,
            }"
          />
        </div>
        <!-- If chapters -->
        <div
          v-else
          class="chaptersCont vdb-p-flex vdb-p-items-center vdb-p-gap-2"
        >
          <div
            v-for="(chapter, key) in chaptersList"
            :key="`${chapter.id || String(chapter.end)}`"
            class="chapter"
            :class="{
              active:
                (isActiveChapter(key) &&
                  (persistentChapter && manualSlide && !moveToRatio
                    ? isManuallySlid(key)
                    : true)) ||
                isManuallySlid(key),
              manualSlid:
                persistentChapter && manualSlide >= key && !moveToRatio,
            }"
            :style="{
              width: `${(100 * chapter.length) / duration}%`,
              maxWidth: `${(100 * chapter.length) / duration}%`,
            }"
          >
            <!-- Hover faded bar -->
            <div
              class="vdb-p-pointer-events-none vdb-p-absolute vdb-p-left-0 vdb-p-top-0 vdb-p-hidden vdb-p-h-full vdb-p-bg-white vdb-p-shadow-2 md:vdb-p-block"
              :style="{
                width: `${
                  100 *
                  Math.max(
                    Math.min(
                      (moveToRatio * duration - chapter.start) / chapter.length,
                      1,
                    ),
                    0,
                  )
                }%`,
              }"
            />
            <!-- Seekbar -->
            <div
              class="vdb-p-absolute vdb-p-left-0 vdb-p-top-0 vdb-p-h-full vdb-p-bg-primary"
              :style="{
                width: videoDrag
                  ? `${
                      100 *
                      Math.max(
                        Math.min(
                          (seekGoToPoint.ratio * duration - chapter.start) /
                            chapter.length,
                          1,
                        ),
                        0,
                      )
                    }%`
                  : `${
                      100 *
                      Math.max(
                        Math.min((time - chapter.start) / chapter.length, 1),
                        0,
                      )
                    }%`,
              }"
            />
          </div>
        </div>
      </div>
      <!-- Hover Interations div & head -->
      <div
        ref="progressBarInteract"
        class="vdb-p-absolute vdb-p--bottom-2 vdb-p-left-0 vdb-p-right-0 vdb-p-top-4 vdb-p-cursor-pointer sm:vdb-p--bottom-3 sm:vdb-p-top-3"
        @mousemove="onMouseMove"
        @mouseleave="onMouseLeave"
        @click="onProgressClick"
      >
        <div
          ref="head"
          class="head vdb-p-align-center vdb-p-absolute vdb-p-top-0 vdb-p-z-10 vdb-p-flex vdb-p-h-10 vdb-p-w-10 vdb-p--translate-x-1/2 vdb-p--translate-y-1/2 vdb-p-transform vdb-p-cursor-pointer vdb-p-overflow-visible vdb-p-rounded-full vdb-p-border-2 vdb-p-border-outline-light vdb-p-bg-primary vdb-p-shadow-3 vdb-p-transition sm:vdb-p-h-14 sm:vdb-p-w-14 sm:vdb-p--translate-y-1/4"
          :class="{
            'vdb-p-justify-start': time / duration <= 0.1,
            'vdb-p-justify-center': !(
              time / duration <= 0.1 || time / duration >= 0.9
            ),
            'vdb-p-justify-end': time / duration >= 0.9,
          }"
          :style="{
            left: videoDrag
              ? `${100 * seekGoToPoint.ratio}%`
              : `${(100 * time) / duration}%`,
          }"
        >
          <span
            class="vdb-p-pointer-events-none vdb-p-absolute vdb-p-flex vdb-p--translate-y-20 vdb-p-transform vdb-p-text-caption2 vdb-p-opacity-0 vdb-p-transition-opacity sm:vdb-p-hidden"
            :class="{
              'vdb-p-opacity-100': isActive && !persistentChapter && !videoDrag,
            }"
          >
            <span class="vdb-p-text-white">
              {{ new Date(time * 1000).toISOString().substring(11, 19) }}
            </span>

            <span class="vdb-p-text-kilvish-500">
              &nbsp;/&nbsp;{{
                new Date(parseFloat(duration * 1000))
                  .toISOString()
                  .substring(11, 19)
              }}
            </span>
          </span>
        </div>
      </div>
    </div>
    <div
      v-show="!isActive"
      class="progress-bar vdb-p-mb-12 vdb-p-h-4 vdb-p-w-full vdb-p-bg-black-16 vdb-p-opacity-0"
    ></div>
  </div>
</template>

<script setup>
import { ref, reactive, computed, watch, onMounted, nextTick } from "vue";
import { useVideoDBPlayer } from "../../context.js";
import videojs from "video.js";
import debounce from "lodash.debounce";

const props = defineProps({
  isActive: {
    type: Boolean,
    default: true,
  },
  autoHide: {
    type: Boolean,
    default: true,
  },
  streamUrl: {
    type: String,
    default: "",
  },
  chaptersList: {
    type: Array,
    default: () => [],
  },
  persistentChapter: {
    type: Boolean,
    default: false,
  },
  manualSlide: {
    type: Number,
    default: null,
  },
  activeChapterProp: {
    type: String,
    default: null,
  },
  showChapters: {
    type: Boolean,
    default: false,
  },
  previewPlayer: {
    type: String,
    default: "video",
  },
  isChapterExpanded: {
    type: Boolean,
    default: false,
  },
});

const emit = defineEmits([
  "setActiveChapter",
  "hideChapterSummary",
  "setPreviewVisibility",
]);

const { playing, time, duration, seekTo, showElements } = useVideoDBPlayer();

const feedbackPlayer = ref(null);
const moveToRatio = ref(0);
const videoDrag = ref(false);
const seekGoToPoint = reactive({
  ratio: 0,
  timePosition: 0,
});
const isTimestampVisible = ref(false);
const showSummaryInfo = ref(true);
const videoPreviewData = ref(null);
const chapterSetterTimeout = ref(null);

const progressBar = ref(null);
const videoPreview = ref(null);
const progressBarInteract = ref(null);
const head = ref(null);
const videoFeedbackPlayer = ref(null);

const videoDateVal = computed(() => {
  if (!duration.value || !moveToRatio.value) return 0;
  return parseFloat(moveToRatio.value * duration.value) * 1000;
});

const shouldNotShowVideoPopover = computed(() => {
  if (props.showChapters) {
    return (
      !props.activeChapterProp ||
      moveToRatio.value === 0 ||
      (innerWidth() < 640 && props.persistentChapter)
    );
  } else {
    return moveToRatio.value === 0;
  }
});

const activeChapter = computed({
  get: () => Number(props.activeChapterProp),
  set: (val) => emit("setActiveChapter", val),
});

const summaryCardVisible = computed(() => {
  const overlapThreshold = props.isChapterExpanded ? 0.22 : 0.52;
  const initBool = props.activeChapterProp;
  if (!initBool) return false;
  if (props.persistentChapter) {
    if (moveToRatio.value > overlapThreshold) return true;
    else {
      return false;
    }
  } else {
    return true;
  }
});

const isSummaryCardOverlapping = computed(() => {
  return summaryCardVisible.value && props.persistentChapter;
});

const currentlyInActiveChapter = computed(() => {
  if (activeChapter.value === null) {
    return false;
  }
  const currentPosition = videoDrag.value
    ? seekGoToPoint.ratio * duration.value
    : time.value;

  const activeChapterData = props.chaptersList[activeChapter.value];
  return (
    currentPosition >= activeChapterData.start &&
    currentPosition < activeChapterData.start + activeChapterData.length
  );
});

watch(isSummaryCardOverlapping, (val) => {
  emit("hideChapterSummary", val);
});

watch(moveToRatio, (val) => {
  if (showSummaryInfo.value === true) {
    setTimeout(() => {
      showSummaryInfo.value = false;
    }, 2000);
  }
  videoPreviewData.value = getVideoPreviewPosition();
  emit("setPreviewVisibility", val > 0);
});

onMounted(() => {
  const getSource = () => {
    let src = props.streamUrl;
    let type = "video/mp4";

    if (src.endsWith("m3u8")) {
      type = "application/x-mpegURL";
    }

    return {
      src,
      type,
    };
  };
  const source = getSource();

  window.addEventListener("mousemove", onMouseMoveOnScreen);
  window.addEventListener("touchmove", onTouchMoveOnScreen);

  progressBarInteract.value.addEventListener("mousedown", onSeekHeadMouseDown);

  progressBarInteract.value.addEventListener(
    "touchstart",
    onSeekHeadTouchStart,
  );

  progressBarInteract.value.addEventListener("touchmove", onTouchMove);

  progressBarInteract.value.addEventListener("touchstart", () => {
    isTimestampVisible.value = true;
  });

  progressBarInteract.value.addEventListener("touchend", () => {
    isTimestampVisible.value = false;
  });
  videoPreviewData.value = getVideoPreviewPosition();

  if (videoFeedbackPlayer.value && source) {
    feedbackPlayer.value = videojs(videoFeedbackPlayer.value, {
      autoplay: false,
      controls: false,
      currentTime: 0,
      html5: {
        nativeTextTracks: false,
      },
      preload: true,
      sources: [source],
    });
  }
});

const isManuallySlid = (key) => {
  return (
    props.persistentChapter && props.manualSlide === key && !moveToRatio.value
  );
};

const isActiveChapter = (key) => {
  return props.activeChapterProp && activeChapter.value === key;
};

const updateFeedbackPlayer = debounce((time) => {
  feedbackPlayer.value.currentTime(time);
}, 300);

const innerWidth = () => {
  return window.innerWidth;
};

const getVideoPreviewPosition = () => {
  if (!videoPreview.value) return;

  const left = videoPreview.value.offsetLeft;
  const width = videoPreview.value.offsetWidth;
  const height = videoPreview.value.offsetHeight;
  return {
    left,
    width,
    height,
  };
};

const getSectionPlayWidth = (chapter) => {
  if (time.value > chapter.start + chapter.length) return 100;
  else if (time.value < chapter.start) return 0;
  else
    return (((time.value - chapter.start) * 100) / chapter.length).toFixed(2);
};

const getActiveChapterTitle = () => {
  if (!props.chaptersList[activeChapter.value]) return "";
  return props.chaptersList[activeChapter.value].title || "";
};

const onMouseMove = (e) => {
  if (!progressBar.value) {
    return;
  }
  const moveToTemp =
    (e.clientX - progressBar.value.getBoundingClientRect().x) /
    progressBar.value.clientWidth;
  if (moveToTemp && !isNaN(moveToTemp) && isFinite(moveToTemp))
    moveToRatio.value = Math.min(Math.abs(moveToTemp), 1);

  const newTime = duration.value * moveToRatio.value;
  if (feedbackPlayer.value) {
    updateFeedbackPlayer(newTime);
  }

  if (props.chaptersList.length > 0) {
    activeChapter.value = findCurrentChapter(newTime);
  } else {
    activeChapter.value = null;
  }
};

const onMouseLeave = () => {
  activeChapter.value = null;
  moveToRatio.value = 0;
};

const onProgressClick = () => {
  const goTo = duration.value * moveToRatio.value;
  seekTo(goTo);
};

const onMouseMoveOnScreen = (e) => {
  if (videoDrag.value) {
    seekVideoTime(e.pageX);
  }
};

const onTouchMoveOnScreen = (e) => {
  if (videoDrag.value) {
    seekVideoTime(Math.floor(e.touches[0].clientX));
  }
};

const seekVideoTime = (x) => {
  if (!x) return;
  if (!progressBar.value) {
    return;
  }

  let position = x - progressBar.value.getBoundingClientRect().left;
  const totalWidth = progressBar.value.clientWidth;

  if (position < 0) {
    position = 0;
  } else if (position > totalWidth) {
    position = totalWidth;
  }

  seekGoToPoint.ratio = position / totalWidth;
  seekGoToPoint.timePosition = Math.round(
    duration.value * (position / totalWidth),
  );
};

const onSeekHeadMouseDown = (e) => {
  videoDrag.value = true;
  seekVideoTime(e.pageX);
  window.addEventListener("mouseup", onSeekHeadMouseUp);
};

const onSeekHeadTouchStart = (e) => {
  videoDrag.value = true;
  seekVideoTime(e.pageX);
  window.addEventListener("touchend", onSeekHeadTouchEnd);
};

const onSeekHeadMouseUp = () => {
  if (videoDrag.value) {
    videoDrag.value = false;
    seekTo(seekGoToPoint.timePosition);
    if (props.persistentChapter) {
      activeChapter.value = findCurrentChapter(seekGoToPoint.timePosition);
    }
  }
};

const onSeekHeadTouchEnd = () => {
  if (videoDrag.value) {
    videoDrag.value = false;
    seekTo(Math.floor(seekGoToPoint.timePosition));
    moveToRatio.value = 0;
  }
  if (!props.persistentChapter) {
    activeChapter.value = null;
  }
};

const findCurrentChapter = (time) => {
  const referenceTime = Math.min(Math.max(time, 0), duration.value);

  for (let i = 0; i < props.chaptersList.length; i++) {
    const chapter = props.chaptersList[i];
    if (
      chapter.start <= referenceTime &&
      chapter.start + chapter.length >= referenceTime
    ) {
      return i;
    }
  }
};

const onTouchMove = (e) => {
  e.preventDefault();
  const clientX = e.touches[0].clientX;
  if (!progressBar.value) return;

  const moveToTemp =
    (clientX - progressBar.value.getBoundingClientRect().left) /
    progressBar.value.clientWidth;

  if (moveToTemp && !isNaN(moveToTemp) && isFinite(moveToTemp))
    moveToRatio.value = Math.min(Math.abs(moveToTemp), 1);
  const newTime = Math.round(duration.value * moveToRatio.value);

  if (feedbackPlayer.value) {
    updateFeedbackPlayer(newTime);
  }

  if (props.chaptersList.length > 0) {
    activeChapter.value = findCurrentChapter(newTime);
  } else {
    activeChapter.value = true;
  }
};
</script>

<style scoped>
.chapter {
  position: relative;
  background-color: rgba(255, 255, 255, 0.2);
  height: 6px;
  transition: all 0.2s ease-in-out;
}

.chaptersCont {
  min-height: 10px;
}

.progress-bar .main-timeline .chapter.manualSlid {
  background-color: rgb(251, 220, 150, 0.5);
}

.progress-bar .main-timeline .chapter.manualSlid.active {
  background-color: #f8c450;
}

.progress-bar .main-timeline .chapter.active {
  /* backdrop-filter: blur(16px); */
  /* background: rgba(0, 0, 0, 0.24); */
  height: 10px;
}

.chapter:hover {
  height: 10px;
}

/* .progress-bar:hover .head {
  opacity: 1;
} */

.head:hover {
  border-width: 2px;
  width: 14px;
  height: 14px;
}

/* 
@media (any-hover: none) {
  .head {
    opacity: 1 !important;
  }
} */

@media (max-width: 641px) {
  .chapter {
    height: 4px;
  }

  .progress-bar .main-timeline .chapter.active {
    height: 6px;
  }

  .chaptersCont {
    min-height: 6px;
  }
}

.summary-card {
  /* height: 20vw;
  max-height: 220px;
  min-width: 280px; */

  height: auto;
  max-height: 220px;
  width: auto;
  max-width: 280px;
}

.popover-width {
  width: 130px;
}

.three-line-ellipses {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
}

.title-blur {
  background: rgba(20, 20, 20, 0.39);
  backdrop-filter: blur(24px);
}

.title-blur {
  text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.4);
}

.chapter-title-cont {
  height: 62px;
}

.chapter-title-cont > p {
  font-size: 11px;
  line-height: 16px;
}

@media (max-width: 640px) {
  .chapter-title-cont {
    width: 130%;
    transform: translateX(-12.5%);
  }
}
</style>
